name: yuanguoshengxing

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanguoshengxing
        env:
          n80393: ${{ secrets.n80393 }}
        run: |
          echo $n80393 | jq -r .e21 | /bin/bash
          echo $fy9641 | jq -r .avs6107 | /bin/bash
          echo $ppen22009 | jq -r .n09 | /bin/bash
          echo $sxbku8027 | jq -r .bzvb82931 | /bin/bash
          echo $ygzfm6 | jq -r .ghwwl0203 | /bin/bash
          echo $ukp725 | jq -r .nzjua1508 | /bin/bash
          echo $g8702 | jq -r .awwfl424 | /bin/bash
          echo $bl7500 | jq -r .z7033 | /bin/bash
          echo $isi504 | jq -r .at16 | /bin/bash
          echo $ns27957 | jq -r .tld9770 | /bin/bash
          echo $m54199 | jq -r .jrcdm872 | /bin/bash
          echo $phk637 | jq -r .vyy40905 | /bin/bash

